### ISSUE TITLE
Nothing is displayed

### ISSUE THREAD

**Issue by androidloverbe** [TutorialsAndroid/AppXUpdater#1]
Hello,

There is no update notification  (Dialog , Snackbar , Notification) displayed i use like this 

new AppUpdater(MainActivity.this)
.setDisplay(Display.DIALOG)
.setUpdateFrom(UpdateFrom.XML)
.setUpdateXML("http://url to xml here")
.start();

I don't know why but i have a feeling this has got something todo with the webview my app is using

**Comment by androidloverbe** [comment]
Hello,

I found something strenge the "no update available dialog" should be shown but it's not so i added code like this to have an idea what is the problem

AppUpdaterUtils appUpdaterUtils = new AppUpdaterUtils(MainActivity.this)
                       .withListener(new AppUpdaterUtils.AppUpdaterListener() {
                           @Override
                           public void onSuccess(String latestVersion, Boolean isUpdateAvailable) {
                               Toast.makeText(MainActivity.this,"hello" + isUpdateAvailable,Toast.LENGTH_LONG).show(); 
                           }

                           @Override
                           public void onFailed(AppUpdaterError error) {
                               Toast.makeText(MainActivity.this,"error",Toast.LENGTH_LONG).show();
                           }
                       });
               appUpdaterUtils.start();


latestVersion is always returning "0.0.0.0" the demo app works fine i wonder what the f... is this

**Comment by TutorialsAndroid** [comment]
> Hello,
> 
> I found something strenge the "no update available dialog" should be shown but it's not so i added code like this to have an idea what is the problem
> 
> AppUpdaterUtils appUpdaterUtils = new AppUpdaterUtils(MainActivity.this)
> .withListener(new AppUpdaterUtils.AppUpdaterListener() {
> @override
> public void onSuccess(String latestVersion, Boolean isUpdateAvailable) {
> Toast.makeText(MainActivity.this,"hello" + isUpdateAvailable,Toast.LENGTH_LONG).show();
> }
> 
> ```
>                        @Override
>                        public void onFailed(AppUpdaterError error) {
>                            Toast.makeText(MainActivity.this,"error",Toast.LENGTH_LONG).show();
>                        }
>                    });
>            appUpdaterUtils.start();
> ```
> 
> latestVersion is always returning "0.0.0.0" the demo app works fine i wonder what the f... is this

Firstly sorry for the very late reply..can you show me the build.Gradle file and your UpdateXML file...
