### ISSUE TITLE
Test update internal version G.Play

### ISSUE THREAD

**Issue by pabmadi** [TutorialsAndroid/AppXUpdater#3]
Hi, I'm triying your library. I upload a new version to internal test of Google Play. After that the Play Store whos that there is a new version; BUT the app always show the snack telling that I have the last version. Y check de log, and i saw that your code is checking to the released app, not to the one that I have in internatl test track...

I want to thet it before release any version. Do you understand? Sorry my english...

**Comment by TutorialsAndroid** [comment]
> Hi, I'm triying your library. I upload a new version to internal test of Google Play. After that the Play Store whos that there is a new version; BUT the app always show the snack telling that I have the last version. Y check de log, and i saw that your code is checking to the released app, not to the one that I have in internatl test track...
> 
> I want to thet it before release any version. Do you understand? Sorry my english...

It only checks for the published release version.
